// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace PracticeGameplayTags
{
	UE5PRACTICE_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that Practice will use
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	UE5PRACTICE_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	UE5PRACTICE_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	UE5PRACTICE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
};
